name: gotong_royong
description: Aplikasi untuk mengorganisir kegiatan gotong royong seperti bersih-bersih lingkungan atau pembangunan fasilitas umum.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  cached_network_image: ^3.2.3
  image_picker: ^1.0.4
  intl: ^0.18.1
  provider: ^6.0.5
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/